# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
    
# Spring Boot
spring:
  activemq:
    in-memory: false
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
  data:
    mongodb:
      uri: mongodb://localhost:27017
      authentication-database: admin
      username: mongouser
      password: Abcd1234

# Camel Spring Boot
camel:
  component:
    jms:
      acknowledgement-mode-name: CLIENT_ACKNOWLEDGE
  springboot:
    name: weldboschmongo

# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.apache.camel: DEBUG
    com.honda: DEBUG

# Application
application:
  mongodb: 
    database: weld2
    collection: bosch2
