apiVersion: "v1"
kind: "Secret"
metadata:
  name: weldboschmongo-secret
data:
  spring.activemq.user: YWRtaW4=
  spring.activemq.password: YWRtaW4=
  spring.data.mongodb.username: bW9uZ291c2Vy
  spring.data.mongodb.password: QWJjZDEyMzQ=
